### ISSUE TITLE
The programme detects a ghost directory

### ISSUE THREAD

**Issue by Daamu32** [Daamu32/Hammer-is-a-good-teacher#2]
I have been doing some tests and it has left me more confused. 
I tried changing the code to a branch that I will upload soon and it worked. I was surprised, because I thought I had only added a try and catch to capture the direction that the console was reading wrongly. I changed back to the old code, ran the project and, surprise, it worked.

So, I downloaded the github repository again and tried to create a new build and run it and it didn't work. The two Utils.cs files are the same (I didn't make any other changes), A capture is attach becasue .cs is not supported.
![image](https://github.com/user-attachments/assets/8a1a48d0-2652-49a5-95d1-132c7e6af7be)

**Comment by Daamu32** [comment]
The branch should now be linked. Use a while(true) because... yeah, I still don't know how to replace them at all. I've really only added the creation of an errors.logs. I could have put it in the normal .log, but I didn't go to much trouble. Maybe now I'll do it

**Comment by Daamu32** [comment]
The updated branch should now be available. Just take a look at it when you really can

**Comment by SSJGodGogeta** [comment]
im srry but i didnt get the error / issue. What ghost directory ? Have you tried debugging it and checking what directory gets returned ? If its a empty directory, then thats normal. That just means that you have inserted an incorrect path. u can build a small check in the main function where it does smth like: if (string.IsEmpty(directory) throw new Error("Directory not found");
