### ISSUE TITLE
Task scheduler automatically deletes download folders

### ISSUE THREAD

**Issue by Daamu32** [Daamu32/Hammer-is-a-good-teacher#4]
The last branch adds (very simply) the ability to recognise the ‘deleteDownloads’ command when executed from the terminal. This causes it to delete the .log files from that location and close the program. Perfect for automations

**Comment by Daamu32** [comment]
At the moment the program is facing the problem that the story editor runs it from System32, which prevents the .log from being generated. Working on a solution

**Comment by Daamu32** [comment]
Completed but not implemented to the main branch (for now)

**Comment by SSJGodGogeta** [comment]
feel free to push it to main if it works
